export const IPC_CHANNELS = {
  TASK_CREATE: 'task:create',
  TASK_UPDATE: 'task:update',
  TASK_START: 'task:start',
  TASK_PAUSE: 'task:pause',
  TASK_STOP: 'task:stop',
  TASK_DELETE: 'task:delete',
  TASK_STATUS_CHANGED: 'task:status-changed',
  TASK_STEP_RESULT: 'task:step-result',
  TASK_LOG: 'task:log',
  TASK_GROUP_CREATE: 'task-group:create',
  TASK_GROUP_UPDATE: 'task-group:update',
  TASK_GROUP_START: 'task-group:start',
  TASK_GROUP_STOP: 'task-group:stop',
  TASK_GROUP_DELETE: 'task-group:delete',
  TASK_GROUP_STATUS_CHANGED: 'task-group:status-changed',
  TASK_GROUP_LOG: 'task-group:log',
  NETWORK_REQUEST: 'network:request',
  CAPTURE_SCREENSHOT: 'capture:screenshot',
  CAPTURE_CLICK: 'capture:click',
  CAPTURE_UPDATED: 'capture:updated',
  LOG_ENTRY: 'log:entry',
  LOG_DEBUG_STATE: 'log:debug-state',
  LOG_SET_DEBUG: 'log:set-debug',
  LOG_GET_LOGS: 'log:get-logs',
  LOG_EXPORT: 'log:export',
  LOG_CLEAR_DISPLAY: 'log:clear-display',
} as const;

export type IPCChannel = (typeof IPC_CHANNELS)[keyof typeof IPC_CHANNELS];
